/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Shopify PDP + Cart Exercise API
 * Minimal frontend-facing contract for the Shopify PDP + cart exercise.
 *
 * It mirrors the subset of the Shopify Storefront API domain the frontend
 * needs: fetch one product for the PDP, create/read a cart, and add lines.
 * Gift wrap and gift message are modeled as cart line attributes
 * (gift_wrap = "true", gift_message = "<free text>") on the product line.
 *
 * The real implementation calls the Storefront GraphQL API directly; this
 * document exists as the domain contract and codegen source (types, zod
 * schemas, MSW mocks).
 *
 * OpenAPI spec version: 3.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

/**
 * Resource identifier (Shopify GID, e.g. gid://shopify/Product/123)
 */
export type Id = string;

export interface Money {
  /** Decimal amount as string, as returned by the Storefront API */
  amount: string;
  /** ISO 4217 currency code */
  currencyCode: string;
}

export interface ErrorResponse {
  /** Technical error code or description */
  message: string;
  /** User-friendly error messages */
  errors?: string[];
}

export interface ProductImage {
  url: string;
  altText?: string;
}

export interface ProductVariant {
  id: Id;
  availableForSale: boolean;
  price: Money;
  compareAtPrice?: Money;
}

/**
 * Product detail for the PDP, with its default (first) variant.
 */
export interface Product {
  id: Id;
  title: string;
  vendor: string;
  image?: ProductImage;
  variant: ProductVariant;
}

/**
 * Key/value attribute attached to a cart line. Gift options use
 * gift_wrap = "true" and gift_message = "<free text>".
 */
export interface CartLineAttribute {
  key: string;
  value: string;
}

export interface CartLine {
  id: Id;
  /** @minimum 1 */
  quantity: number;
  /** Product title of the line's merchandise */
  title: string;
  vendor: string;
  image?: ProductImage;
  lineTotal: Money;
  attributes: CartLineAttribute[];
}

export interface Cart {
  id: Id;
  /** @minimum 0 */
  totalQuantity: number;
  subtotal: Money;
  lines: CartLine[];
}

/**
 * A variant to add to the cart, with optional gift attributes.
 */
export interface CartLineInput {
  merchandiseId: Id;
  /** @minimum 1 */
  quantity: number;
  attributes?: CartLineAttribute[];
}

export interface CreateCartRequest {
  /** Optional initial lines */
  lines?: CartLineInput[];
}

export interface AddCartLinesRequest {
  /** @minItems 1 */
  lines: CartLineInput[];
}

/**
 * Resource not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Validation failed
 */
export type ValidationErrorResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export const getShopifyPDPCartExerciseAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * Returns one product with its default variant, price and compare-at price.
 * @summary Get product detail for the PDP
 */
const getProduct = (
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    return axiosInstance.get(
      `/products/${productId}`,options
    );
  }

/**
 * Creates a new cart, optionally with initial lines and gift attributes.
 * @summary Create a cart (Storefront cartCreate)
 */
const createCart = (
    createCartRequest?: CreateCartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Cart>> => {
    return axiosInstance.post(
      `/cart`,
      createCartRequest,options
    );
  }

/**
 * Returns the cart with its lines, totals and gift wrap/message attributes.
 * @summary Get cart contents, including gift attributes
 */
const getCart = (
    cartId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Cart>> => {
    return axiosInstance.get(
      `/cart/${cartId}`,options
    );
  }

/**
 * Adds variant lines with quantity and optional gift_wrap/gift_message attributes.
 * @summary Add product variant lines to the cart (Storefront cartLinesAdd)
 */
const addCartLines = (
    cartId: string,
    addCartLinesRequest: AddCartLinesRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Cart>> => {
    return axiosInstance.post(
      `/cart/${cartId}/lines`,
      addCartLinesRequest,options
    );
  }

return {getProduct,createCart,getCart,addCartLines}};
export type GetProductResult = AxiosResponse<Product>
export type CreateCartResult = AxiosResponse<Cart>
export type GetCartResult = AxiosResponse<Cart>
export type AddCartLinesResult = AxiosResponse<Cart>


export const getGetProductResponseMock = (overrideResponse: Partial<Extract<Product, object>> = {}): Product => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), vendor: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.helpers.arrayElement([{url: faker.internet.url(), altText: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), variant: {id: faker.string.alpha({length: {min: 10, max: 20}}), availableForSale: faker.datatype.boolean(), price: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, compareAtPrice: faker.helpers.arrayElement([{amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, undefined])}, ...overrideResponse})

export const getCreateCartResponseMock = (overrideResponse: Partial<Extract<Cart, object>> = {}): Cart => ({id: faker.string.alpha({length: {min: 10, max: 20}}), totalQuantity: faker.number.int({min: 0}), subtotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, lines: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), quantity: faker.number.int({min: 1}), title: faker.string.alpha({length: {min: 10, max: 20}}), vendor: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.helpers.arrayElement([{url: faker.internet.url(), altText: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), lineTotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, attributes: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({key: faker.string.alpha({length: {min: 10, max: 20}}), value: faker.string.alpha({length: {min: 10, max: 20}})}))})), ...overrideResponse})

export const getGetCartResponseMock = (overrideResponse: Partial<Extract<Cart, object>> = {}): Cart => ({id: faker.string.alpha({length: {min: 10, max: 20}}), totalQuantity: faker.number.int({min: 0}), subtotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, lines: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), quantity: faker.number.int({min: 1}), title: faker.string.alpha({length: {min: 10, max: 20}}), vendor: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.helpers.arrayElement([{url: faker.internet.url(), altText: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), lineTotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, attributes: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({key: faker.string.alpha({length: {min: 10, max: 20}}), value: faker.string.alpha({length: {min: 10, max: 20}})}))})), ...overrideResponse})

export const getAddCartLinesResponseMock = (overrideResponse: Partial<Extract<Cart, object>> = {}): Cart => ({id: faker.string.alpha({length: {min: 10, max: 20}}), totalQuantity: faker.number.int({min: 0}), subtotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, lines: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), quantity: faker.number.int({min: 1}), title: faker.string.alpha({length: {min: 10, max: 20}}), vendor: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.helpers.arrayElement([{url: faker.internet.url(), altText: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), lineTotal: {amount: faker.string.alpha({length: {min: 10, max: 20}}), currencyCode: faker.string.alpha({length: {min: 10, max: 20}})}, attributes: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({key: faker.string.alpha({length: {min: 10, max: 20}}), value: faker.string.alpha({length: {min: 10, max: 20}})}))})), ...overrideResponse})


export const getGetProductMockHandler = (overrideResponse?: Product | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Product> | Product), options?: RequestHandlerOptions) => {
  return http.get('*/products/:productId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateCartMockHandler = (overrideResponse?: Cart | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Cart> | Cart), options?: RequestHandlerOptions) => {
  return http.post('*/cart', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCartResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetCartMockHandler = (overrideResponse?: Cart | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Cart> | Cart), options?: RequestHandlerOptions) => {
  return http.get('*/cart/:cartId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCartResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAddCartLinesMockHandler = (overrideResponse?: Cart | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Cart> | Cart), options?: RequestHandlerOptions) => {
  return http.post('*/cart/:cartId/lines', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddCartLinesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getShopifyPDPCartExerciseAPIMock = () => [
  getGetProductMockHandler(),
  getCreateCartMockHandler(),
  getGetCartMockHandler(),
  getAddCartLinesMockHandler()]
