/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import { apiMutator } from '../app/utils/apiMutator';
/**
 * 1-based page index
 * @minimum 1
 */
export type Page = number;

/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
export type PageSize = number;

/**
 * Resource identifier
 */
export type Id = string;

/**
 * Free-text search string
 * @minLength 1
 */
export type Text = string;

export type Email = string;

/**
 * @minLength 8
 */
export type Password = string;

export interface PaginationMeta {
  page: Page;
  pageSize: PageSize;
  /** @minimum 0 */
  totalItems: number;
  /** @minimum 0 */
  totalPages: number;
}

export interface MessageResponse {
  success: true;
  status: number;
  message: string;
}

export interface ErrorResponse {
  success: false;
  status: number;
  /** Technical error code or description */
  message: string;
  /** User-friendly error messages */
  errors: string[];
}

export interface ValidationErrorResponse {
  success: false;
  status: number;
  message: string;
  /** Validation error messages */
  errors: string[];
}

export interface SuccessEnvelope {
  success: true;
  status: number;
  message: string;
}

export interface AuthTokens {
  /** Access JWT */
  token: string;
  /** Refresh token if returned by backend */
  refreshToken?: string;
  /** Access token expiry in seconds */
  expiresIn?: number;
}

export type AuthTokensEnvelope = SuccessEnvelope & {
  data: AuthTokens;
};

export interface RefreshTokenResponse {
  /** New access JWT */
  token: string;
  /** New refresh token if returned by backend */
  refreshToken?: string;
  /** New access token expiry in seconds */
  expiresIn?: number;
}

export type RefreshTokenEnvelope = SuccessEnvelope & {
  data: RefreshTokenResponse;
};

export interface User {
  id: Id;
  email: Email;
  username: string;
  admin?: boolean;
  active?: boolean;
  imageUrl?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type UserEnvelope = SuccessEnvelope & {
  data: User;
};

export interface UsersResponse {
  items: User[];
  meta: PaginationMeta;
}

export type UsersResponseEnvelope = SuccessEnvelope & {
  data: UsersResponse;
};

export interface Product {
  id: Id;
  title: string;
  /** @minimum 0 */
  price: number;
  description?: string;
  active?: boolean;
  imageUrl?: string;
  categories?: string[];
  tags?: string[];
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
}

export type ProductEnvelope = SuccessEnvelope & {
  data: Product;
};

export interface ProductsResponse {
  items: Product[];
  meta: PaginationMeta;
}

export type ProductsResponseEnvelope = SuccessEnvelope & {
  data: ProductsResponse;
};

export interface OrderItem {
  product: Product;
  /** @minimum 1 */
  quantity: number;
}

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  pending: 'pending',
  paid: 'paid',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;

export interface Order {
  id: Id;
  userId: Id;
  email: Email;
  items: OrderItem[];
  /** @minimum 0 */
  total: number;
  /** Optional order notes */
  notes?: string;
  status: OrderStatus;
  createdAt?: string;
  updatedAt?: string;
}

export type OrderEnvelope = SuccessEnvelope & {
  data: Order;
};

export interface OrdersResponse {
  items: Order[];
  meta: PaginationMeta;
}

export type OrdersResponseEnvelope = SuccessEnvelope & {
  data: OrdersResponse;
};

export type FeedbackRequestStatus = typeof FeedbackRequestStatus[keyof typeof FeedbackRequestStatus];


export const FeedbackRequestStatus = {
  new: 'new',
  in_progress: 'in_progress',
  resolved: 'resolved',
  spam: 'spam',
} as const;

export interface FeedbackRequest {
  id: Id;
  name?: string;
  email: Email;
  subject: string;
  message: string;
  status: FeedbackRequestStatus;
  adminNotes?: string;
  respondedAt?: string;
  createdAt: string;
  updatedAt?: string;
}

export type FeedbackRequestEnvelope = SuccessEnvelope & {
  data: FeedbackRequest;
};

export interface FeedbackRequestsResponse {
  items: FeedbackRequest[];
  meta: PaginationMeta;
}

export type FeedbackRequestsResponseEnvelope = SuccessEnvelope & {
  data: FeedbackRequestsResponse;
};

export interface CartItem {
  productId: Id;
  /** @minimum 1 */
  quantity: number;
}

export interface CartSummaryResponse {
  /**
     * Number of distinct cart lines/items
     * @minimum 0
     */
  itemsCount: number;
  /**
     * Sum of quantities across all items
     * @minimum 0
     */
  totalQuantity: number;
  /**
     * Sum of item prices * quantity (before tax/shipping/discounts)
     * @minimum 0
     */
  total: number;
  /** ISO-4217 currency code (e.g. USD) */
  currency?: string;
}

export interface CartResponse {
  items: CartItem[];
  summary: CartSummaryResponse;
}

export type CartResponseEnvelope = SuccessEnvelope & {
  data: CartResponse;
};

export type CartSummaryResponseEnvelope = SuccessEnvelope & {
  data: CartSummaryResponse;
};

export interface CheckoutResponse {
  order: Order;
  message?: string;
}

export type CheckoutResponseEnvelope = SuccessEnvelope & {
  data: CheckoutResponse;
};

export type AdminHealthStatus = typeof AdminHealthStatus[keyof typeof AdminHealthStatus];


export const AdminHealthStatus = {
  ok: 'ok',
  degraded: 'degraded',
} as const;

export type AdminHealthDatabaseStatus = typeof AdminHealthDatabaseStatus[keyof typeof AdminHealthDatabaseStatus];


export const AdminHealthDatabaseStatus = {
  connected: 'connected',
  connecting: 'connecting',
  disconnected: 'disconnected',
} as const;

export interface AdminHealthIntegrations {
  loki?: boolean;
  posthog?: boolean;
  otelEnabled?: boolean;
}

export interface AdminHealthMemory {
  heapUsedMb: number;
  heapTotalMb: number;
  rssMb: number;
}

export interface AdminHealthSystem {
  platform: string;
  cpuCount: number;
  loadAvg: number[];
}

export type AdminHealthDatabase = {
  status: AdminHealthDatabaseStatus;
};

export interface AdminHealth {
  status: AdminHealthStatus;
  environment: string;
  service: string;
  nodeVersion: string;
  /** @minimum 0 */
  uptimeSeconds: number;
  database: AdminHealthDatabase;
  integrations?: AdminHealthIntegrations;
  memory?: AdminHealthMemory;
  system?: AdminHealthSystem;
  timestamp: string;
}

export interface AdminHealthResponse {
  success: true;
  data: AdminHealth;
}

export type AdminHealthResponseEnvelope = SuccessEnvelope & {
  data: AdminHealthResponse;
};

export interface AdminMetricsLatency {
  /** Median latency in ms */
  p50: number;
  /** 95th-percentile latency in ms */
  p95: number;
}

export type AdminMetricsSummaryHttp = {
  /** @minimum 0 */
  totalRequests: number;
  /** @minimum 0 */
  totalErrors: number;
  /**
     * Fraction of requests that returned 4xx/5xx
     * @minimum 0
     * @maximum 1
     */
  errorRate: number;
  /** @minimum 0 */
  inFlight: number;
  latencyMs: AdminMetricsLatency;
};

export type AdminMetricsSummaryAuth = {
  /** @minimum 0 */
  loginSuccess?: number;
  /** @minimum 0 */
  loginFailure?: number;
  /** @minimum 0 */
  signupSuccess?: number;
};

export type AdminMetricsSummaryBusiness = {
  /** @minimum 0 */
  checkoutSuccess?: number;
  /** @minimum 0 */
  ordersCreated?: number;
};

export type AdminMetricsSummaryDatabase = {
  /** @minimum 0 */
  queriesTotal?: number;
  /** @minimum 0 */
  errorsTotal?: number;
};

export type AdminMetricsSummaryProcess = {
  /** @minimum 0 */
  uptimeSeconds?: number;
  /** @minimum 0 */
  heapUsedMb?: number;
};

export interface AdminMetricsSummary {
  http: AdminMetricsSummaryHttp;
  auth: AdminMetricsSummaryAuth;
  business: AdminMetricsSummaryBusiness;
  database: AdminMetricsSummaryDatabase;
  process: AdminMetricsSummaryProcess;
  timestamp: string;
}

export interface AdminMetricsSummaryResponse {
  success: true;
  data: AdminMetricsSummary;
}

export type AdminMetricsSummaryResponseEnvelope = SuccessEnvelope & {
  data: AdminMetricsSummaryResponse;
};

export type AuditEventItemActorRole = typeof AuditEventItemActorRole[keyof typeof AuditEventItemActorRole];


export const AuditEventItemActorRole = {
  admin: 'admin',
  user: 'user',
  anonymous: 'anonymous',
} as const;

export type AuditEventItemOutcome = typeof AuditEventItemOutcome[keyof typeof AuditEventItemOutcome];


export const AuditEventItemOutcome = {
  success: 'success',
  failure: 'failure',
} as const;

export type AuditEventItemLevel = typeof AuditEventItemLevel[keyof typeof AuditEventItemLevel];


export const AuditEventItemLevel = {
  info: 'info',
  warn: 'warn',
} as const;

export type AuditEventItemMetadata = { [key: string]: unknown };

export interface AuditEventItem {
  actor_user_id: string;
  actor_role: AuditEventItemActorRole;
  /** Dot-notation action name (e.g. auth.login.succeeded) */
  action: string;
  outcome: AuditEventItemOutcome;
  ip?: string;
  user_agent?: string;
  request_id?: string;
  trace_id?: string;
  target_type?: string;
  target_id?: string;
  metadata?: AuditEventItemMetadata;
  timestamp: string;
  level: AuditEventItemLevel;
}

export type AuditLogsResponseData = {
  items: AuditEventItem[];
  /** @minimum 0 */
  total: number;
};

export interface AuditLogsResponse {
  success: true;
  data: AuditLogsResponseData;
}

export type AuditLogsResponseEnvelope = SuccessEnvelope & {
  data: AuditLogsResponse;
};

export interface LoginRequest {
  email: Email;
  password: Password;
}

export interface SignupRequest {
  email: Email;
  /** @minLength 3 */
  username: string;
  password: Password;
  passwordConfirm: Password;
  imageUrl?: string;
}

export interface SignupRequestMultipart {
  email: Email;
  /** @minLength 3 */
  username: string;
  password: Password;
  passwordConfirm: Password;
  /** Optional user profile image */
  imageUpload?: Blob;
}

export interface PasswordResetRequest {
  email: Email;
}

export interface PasswordResetConfirmRequest {
  /** One-time password reset token (NOT a JWT). */
  token: string;
  password: Password;
  passwordConfirm: Password;
}

export interface AccountDeleteConfirmRequest {
  /** One-time account deletion token (NOT a JWT). */
  token: string;
}

export interface SearchUsersRequest {
  page?: Page;
  pageSize?: PageSize;
  text?: Text;
  id?: Id;
  email?: Email;
  username?: string;
  active?: boolean;
}

export interface CreateUserRequest {
  email: Email;
  username: string;
  password: Password;
  admin?: boolean;
  active?: boolean;
  imageUrl?: string;
}

export interface CreateUserRequestMultipart {
  email: Email;
  username: string;
  password: Password;
  admin?: boolean;
  active?: boolean;
  /** Optional user profile image */
  imageUpload?: Blob;
}

export interface UpdateUserRequest {
  id: Id;
  email?: Email;
  username?: string;
  password?: Password;
  imageUrl?: string;
}

export interface UpdateUserRequestMultipart {
  id: Id;
  email?: Email;
  username?: string;
  password?: Password;
  /** Optional user profile image */
  imageUpload?: Blob;
}

export interface UpdateUserByIdRequest {
  email?: Email;
  password?: Password;
  username?: string;
  imageUrl?: string;
}

export interface UpdateUserByIdRequestMultipart {
  email?: Email;
  password?: Password;
  username?: string;
  /** Optional user profile image */
  imageUpload?: Blob;
}

export interface DeleteUserRequest {
  id: Id;
  hardDelete?: boolean;
}

export interface SearchProductsRequest {
  page?: Page;
  pageSize?: PageSize;
  text?: Text;
  id?: Id;
  /** @minimum 0 */
  minPrice?: number;
  /** @minimum 0 */
  maxPrice?: number;
  category?: string;
  tag?: string;
}

export interface CreateProductRequest {
  title: string;
  /** @minimum 0 */
  price: number;
  description?: string;
  active?: boolean;
  imageUrl?: string;
  categories?: string[];
  tags?: string[];
}

export interface CreateProductRequestMultipart {
  title: string;
  /** @minimum 0 */
  price: number;
  description?: string;
  active?: boolean;
  /** Optional product image */
  imageUpload?: Blob;
  categories?: string[];
  tags?: string[];
}

export interface UpdateProductRequest {
  id: Id;
  title: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  active?: boolean;
  imageUrl?: string;
  categories?: string[];
  tags?: string[];
}

export interface UpdateProductRequestMultipart {
  id: Id;
  title: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  active?: boolean;
  /** Optional product image */
  imageUpload?: Blob;
  categories?: string[];
  tags?: string[];
}

export interface UpdateProductByIdRequest {
  title: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  active?: boolean;
  imageUrl?: string;
  categories?: string[];
  tags?: string[];
}

export interface UpdateProductByIdRequestMultipart {
  title: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  active?: boolean;
  /** Optional product image */
  imageUpload?: Blob;
  categories?: string[];
  tags?: string[];
}

export interface DeleteProductRequest {
  id: Id;
  hardDelete?: boolean;
}

export interface UpsertCartItemRequest {
  productId: Id;
  /** @minimum 1 */
  quantity: number;
}

export interface UpdateCartItemByIdRequest {
  productId?: Id;
  /** @minimum 1 */
  quantity: number;
}

export interface RemoveCartItemRequest {
  productId?: Id;
}

export interface CheckoutRequest {
  email?: Email;
  /** Optional order notes */
  notes?: string;
}

export interface SearchOrdersRequest {
  page?: Page;
  pageSize?: PageSize;
  id?: Id;
  userId?: Id;
  productId?: Id;
  email?: Email;
}

/**
 * Create a new order.
 */
export interface CreateOrderRequest {
  userId: Id;
  email: Email;
  /** @minItems 1 */
  items: CartItem[];
}

/**
 * Updated order status
 */
export type UpdateOrderRequestStatus = typeof UpdateOrderRequestStatus[keyof typeof UpdateOrderRequestStatus];


export const UpdateOrderRequestStatus = {
  pending: 'pending',
  paid: 'paid',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;

export interface UpdateOrderRequest {
  id: Id;
  /** Updated order status */
  status?: UpdateOrderRequestStatus;
  userId?: Id;
  email?: Email;
  /** @minItems 1 */
  items?: CartItem[];
}

/**
 * Updated order status
 */
export type UpdateOrderByIdRequestStatus = typeof UpdateOrderByIdRequestStatus[keyof typeof UpdateOrderByIdRequestStatus];


export const UpdateOrderByIdRequestStatus = {
  pending: 'pending',
  paid: 'paid',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const;

export interface UpdateOrderByIdRequest {
  /** Updated order status */
  status?: UpdateOrderByIdRequestStatus;
  userId?: Id;
  email?: Email;
  /** @minItems 1 */
  items?: CartItem[];
}

export interface DeleteOrderRequest {
  id: Id;
}

export interface CreateFeedbackRequest {
  name?: string;
  email: Email;
  subject: string;
  message: string;
}

export type SearchFeedbackRequestsRequestStatus = typeof SearchFeedbackRequestsRequestStatus[keyof typeof SearchFeedbackRequestsRequestStatus];


export const SearchFeedbackRequestsRequestStatus = {
  new: 'new',
  in_progress: 'in_progress',
  resolved: 'resolved',
  spam: 'spam',
} as const;

export interface SearchFeedbackRequestsRequest {
  page?: Page;
  pageSize?: PageSize;
  text?: Text;
  status?: SearchFeedbackRequestsRequestStatus;
  email?: Email;
}

export type UpdateFeedbackRequestStatusRequestStatus = typeof UpdateFeedbackRequestStatusRequestStatus[keyof typeof UpdateFeedbackRequestStatusRequestStatus];


export const UpdateFeedbackRequestStatusRequestStatus = {
  new: 'new',
  in_progress: 'in_progress',
  resolved: 'resolved',
  spam: 'spam',
} as const;

export interface UpdateFeedbackRequestStatusRequest {
  status?: UpdateFeedbackRequestStatusRequestStatus;
  adminNotes?: string;
}

/**
 * Success
 */
export type SuccessResponse = MessageResponse;

/**
 * Unauthorized
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Forbidden
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Resource not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export type PageParamParameter = Page;

export type PageSizeParamParameter = PageSize;

export type TextParamParameter = Text;

export type IdParamParameter = Id;

export type UserIdParamParameter = Id;

export type ProductIdParamParameter = Id;

export type GetObservabilityAuditLogsParams = {
/**
 * Filter by actor user ID
 */
actor?: string;
/**
 * Filter by action name (e.g. auth.login.failed)
 */
action?: string;
/**
 * Filter by outcome
 */
outcome?: GetObservabilityAuditLogsOutcome;
/**
 * Return events after this ISO-8601 timestamp
 */
since?: string;
/**
 * Maximum number of events to return
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GetObservabilityAuditLogsOutcome = typeof GetObservabilityAuditLogsOutcome[keyof typeof GetObservabilityAuditLogsOutcome];


export const GetObservabilityAuditLogsOutcome = {
  success: 'success',
  failure: 'failure',
} as const;

export type ListUsersParams = {
/**
 * 1-based page index
 * @minimum 1
 */
page?: PageParamParameter;
/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParamParameter;
/**
 * Free-text search string
 * @minLength 1
 */
text?: TextParamParameter;
/**
 * Resource identifier
 */
id?: IdParamParameter;
email?: Email;
username?: string;
active?: boolean;
};

export type DeleteUserByIdParams = {
hardDelete?: boolean;
};

export type ListProductsParams = {
/**
 * 1-based page index
 * @minimum 1
 */
page?: PageParamParameter;
/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParamParameter;
/**
 * Free-text search string
 * @minLength 1
 */
text?: TextParamParameter;
/**
 * Resource identifier
 */
productId?: ProductIdParamParameter;
/**
 * @minimum 0
 */
minPrice?: number;
/**
 * @minimum 0
 */
maxPrice?: number;
};

export type DeleteProductByIdParams = {
hardDelete?: boolean;
};

export type ListOrdersParams = {
/**
 * 1-based page index
 * @minimum 1
 */
page?: PageParamParameter;
/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParamParameter;
/**
 * Resource identifier
 */
id?: IdParamParameter;
/**
 * Resource identifier
 */
userId?: UserIdParamParameter;
/**
 * Resource identifier
 */
productId?: ProductIdParamParameter;
email?: Email;
};

export const getEcommerceDemoAPI = () => {
/**
 * Public ping endpoint. Returns a simple liveness indicator confirming the API process is running.
 * @summary API health check
 */
const getHealth = (

 ) => {
      return apiMutator<MessageResponse>(
      {url: `/`, method: 'GET'
    },
      );
    }

/**
 * Live Server-Sent Events stream for demo dashboards.
 * Sends `metrics.snapshot` on connect, followed by periodic `metrics.updated` and `heartbeat` events.
 * @summary Observability SSE stream
 */
const getObservabilityEvents = (

 ) => {
      return apiMutator<string>(
      {url: `/observability/events`, method: 'GET'
    },
      );
    }

/**
 * Full JSON health snapshot for dashboard use.
 * Includes uptime, database status, memory, integrations, and system info.
 * Requires admin role.
 * @summary Health snapshot
 */
const getObservabilityHealth = (

 ) => {
      return apiMutator<AdminHealthResponseEnvelope>(
      {url: `/observability/health`, method: 'GET'
    },
      );
    }

/**
 * Raw Prometheus text (exposition format 0.0.4).
 * Intended for Prometheus scraping, not for browser clients.
 * Use `GET /observability/metrics/overview` for a JSON summary suitable for dashboards.
 * @summary Prometheus metrics
 */
const getObservabilityMetrics = (

 ) => {
      return apiMutator<string>(
      {url: `/observability/metrics`, method: 'GET'
    },
      );
    }

/**
 * Key operational metrics derived from Prometheus counters/histograms,
 * returned as structured JSON for dashboard KPI cards and charts.
 * Requires admin role.
 * @summary Metrics overview (JSON)
 */
const getObservabilityMetricsOverview = (

 ) => {
      return apiMutator<AdminMetricsSummaryResponseEnvelope>(
      {url: `/observability/metrics/overview`, method: 'GET'
    },
      );
    }

/**
 * Returns the most recent audit events from the in-memory ring buffer (up to 200).
 * Events include auth flows, admin CRUD actions, and security blocks.
 * Requires admin role.
 * @summary Recent audit events
 */
const getObservabilityAuditLogs = (
    params?: GetObservabilityAuditLogsParams,
 ) => {
      return apiMutator<AuditLogsResponseEnvelope>(
      {url: `/observability/audit`, method: 'GET',
        params
    },
      );
    }

/**
 * Returns the full profile of the currently authenticated user
 * @summary Current user info
 */
const getAccount = (

 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/account`, method: 'GET'
    },
      );
    }

/**
 * Initiates the account-deletion flow for the authenticated user. A one-time confirmation token is sent to the user's email address. The token must then be submitted to `/account/delete-confirm` to complete the deletion.
 * @summary Request account deletion
 */
const requestAccountDelete = (

 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account`, method: 'DELETE'
    },
      );
    }

/**
 * Completes the account-deletion flow. Validates the one-time token issued by `DELETE /account` and, if valid, permanently removes the user account.
 * @summary Confirm account deletion
 */
const confirmAccountDelete = (
    accountDeleteConfirmRequest: AccountDeleteConfirmRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account/delete-confirm`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: accountDeleteConfirmRequest
    },
      );
    }

/**
 * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
 * @summary Login
 */
const login = (
    loginRequest: LoginRequest,
 ) => {
      return apiMutator<AuthTokensEnvelope>(
      {url: `/account/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }

/**
 * Registers a new user account with optional image upload. Returns the newly created user profile on success.
 * @summary Signup
 */
const signup = (
    signupBody: SignupRequest | SignupRequestMultipart,
 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/account/signup`, method: 'POST',
      data: signupBody
    },
      );
    }

/**
 * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
 */
const requestPasswordReset = (
    passwordResetRequest: PasswordResetRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account/reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetRequest
    },
      );
    }

/**
 * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user's password to the supplied value.
 */
const confirmPasswordReset = (
    passwordResetConfirmRequest: PasswordResetConfirmRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account/reset-confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirmRequest
    },
      );
    }

/**
 * Creates a new short-lived access token using a refresh token. The refresh token can be provided as a query parameter, path parameter, or retrieved from the `jwt` cookie.
 * @summary Refresh access token
 */
const refreshToken = (

 ) => {
      return apiMutator<RefreshTokenEnvelope>(
      {url: `/account/refresh`, method: 'GET'
    },
      );
    }

/**
 * Creates a new short-lived access token using a refresh token provided in the URL path.
 * @summary Refresh access token with token in path
 */
const refreshTokenWithPath = (
    token: string,
 ) => {
      return apiMutator<RefreshTokenEnvelope>(
      {url: `/account/refresh/${token}`, method: 'GET'
    },
      );
    }

/**
 * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
 * @summary Logout from all devices
 */
const logoutAll = (

 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account/logout-all`, method: 'POST'
    },
      );
    }

/**
 * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
 * @summary Remove expired tokens
 */
const deleteExpiredTokens = (

 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/account/tokens/expired`, method: 'DELETE'
    },
      );
    }

/**
 * Returns a paginated list of user accounts.
 * @summary List users (paginated)
 */
const listUsers = (
    params?: ListUsersParams,
 ) => {
      return apiMutator<UsersResponseEnvelope>(
      {url: `/users`, method: 'GET',
        params
    },
      );
    }

/**
 * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
 * @summary Create user
 */
const createUser = (
    createUserBody: CreateUserRequest | CreateUserRequestMultipart,
 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/users`, method: 'POST',
      data: createUserBody
    },
      );
    }

/**
 * Updates an existing user's email or password. Optional image can be uploaded.
 * @summary Edit user
 */
const updateUser = (
    updateUserBody: UpdateUserRequest | UpdateUserRequestMultipart,
 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/users`, method: 'PUT',
      data: updateUserBody
    },
      );
    }

/**
 * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
 * @summary Delete user
 */
const deleteUser = (
    deleteUserRequest: DeleteUserRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/users`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserRequest
    },
      );
    }

/**
 * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
 * @summary User details
 */
const getUserById = (
    id: string,
 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/users/${id}`, method: 'GET'
    },
      );
    }

/**
 * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
 * @summary Edit user
 */
const updateUserById = (
    id: string,
    updateUserByIdBody: UpdateUserByIdRequest | UpdateUserByIdRequestMultipart,
 ) => {
      return apiMutator<UserEnvelope>(
      {url: `/users/${id}`, method: 'PUT',
      data: updateUserByIdBody
    },
      );
    }

/**
 * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
 * @summary Delete user
 */
const deleteUserById = (
    id: string,
    params?: DeleteUserByIdParams,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/users/${id}`, method: 'DELETE',
        params
    },
      );
    }

/**
 * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
 * @summary Search users (DTO-friendly)
 */
const searchUsers = (
    searchUsersRequest: SearchUsersRequest,
 ) => {
      return apiMutator<UsersResponseEnvelope>(
      {url: `/users/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchUsersRequest
    },
      );
    }

/**
 * Creates a user feedback/contact request and notifies admins via email.
 * @summary Submit contact request
 */
const createFeedbackRequest = (
    createFeedbackRequest: CreateFeedbackRequest,
 ) => {
      return apiMutator<FeedbackRequestEnvelope>(
      {url: `/feedback/contact`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFeedbackRequest
    },
      );
    }

/**
 * Returns feedback/contact requests for admin review.
 * @summary List feedback requests
 */
const listFeedbackRequests = (
    searchFeedbackRequestsRequest?: SearchFeedbackRequestsRequest,
 ) => {
      return apiMutator<FeedbackRequestsResponseEnvelope>(
      {url: `/feedback`, method: 'GET',
      headers: {'Content-Type': 'application/json', }
    },
      );
    }

/**
 * Updates status/notes of a feedback request.
 * @summary Update feedback request status
 */
const updateFeedbackRequestStatus = (
    id: string,
    updateFeedbackRequestStatusRequest: UpdateFeedbackRequestStatusRequest,
 ) => {
      return apiMutator<FeedbackRequestEnvelope>(
      {url: `/feedback/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFeedbackRequestStatusRequest
    },
      );
    }

/**
 * Returns a paginated list of products.
 * @summary List products (paginated)
 */
const listProducts = (
    params?: ListProductsParams,
 ) => {
      return apiMutator<ProductsResponseEnvelope>(
      {url: `/products`, method: 'GET',
        params
    },
      );
    }

/**
 * Creates a new product with optional image upload
 * @summary Create product
 */
const createProduct = (
    createProductBody: CreateProductRequest | CreateProductRequestMultipart,
 ) => {
      return apiMutator<ProductEnvelope>(
      {url: `/products`, method: 'POST',
      data: createProductBody
    },
      );
    }

/**
 * Updates an existing product with optional image upload
 * @summary Edit product
 */
const updateProduct = (
    updateProductBody: UpdateProductRequest | UpdateProductRequestMultipart,
 ) => {
      return apiMutator<ProductEnvelope>(
      {url: `/products`, method: 'PUT',
      data: updateProductBody
    },
      );
    }

/**
 * Deletes the product identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record
 * @summary Delete product
 */
const deleteProduct = (
    deleteProductRequest: DeleteProductRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/products`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteProductRequest
    },
      );
    }

/**
 * Returns the full details of the product identified by `{id}`. Functionally equivalent to `GET /products?id={id}`.
 * @summary Product details
 */
const getProductById = (
    id: string,
 ) => {
      return apiMutator<ProductEnvelope>(
      {url: `/products/${id}`, method: 'GET'
    },
      );
    }

/**
 * Updates the product identified by `{id}` in the path with optional image upload. Functionally equivalent to `PUT /products` with the id in the body.
 * @summary Edit product
 */
const updateProductById = (
    id: string,
    updateProductByIdBody: UpdateProductByIdRequest | UpdateProductByIdRequestMultipart,
 ) => {
      return apiMutator<ProductEnvelope>(
      {url: `/products/${id}`, method: 'PUT',
      data: updateProductByIdBody
    },
      );
    }

/**
 * Deletes the product identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /products`.
 * @summary Delete product
 */
const deleteProductById = (
    id: string,
    params?: DeleteProductByIdParams,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/products/${id}`, method: 'DELETE',
        params
    },
      );
    }

/**
 * Searches and filters products via a JSON request body. Functionally equivalent to `GET /products` with query parameters.
 * @summary Search products (DTO-friendly)
 */
const searchProducts = (
    searchProductsRequest: SearchProductsRequest,
 ) => {
      return apiMutator<ProductsResponseEnvelope>(
      {url: `/products/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchProductsRequest
    },
      );
    }

/**
 * Returns all items currently in the authenticated user's cart along with a computed summary
 * @summary Get cart
 */
const getCart = (

 ) => {
      return apiMutator<CartResponseEnvelope>(
      {url: `/cart`, method: 'GET'
    },
      );
    }

/**
 * Adds or edit a product to the authenticated user's cart. Returns the updated cart.
 * @summary Add/Edit cart item
 */
const upsertCartItem = (
    upsertCartItemRequest: UpsertCartItemRequest,
 ) => {
      return apiMutator<CartResponseEnvelope>(
      {url: `/cart`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: upsertCartItemRequest
    },
      );
    }

/**
 * Clear cart or, ir productId is set, removes a specific product from the authenticated user's cart. Returns the updated cart (can be empty)
 * @summary Empty cart or, if productId is set, remove target cart item
 */
const clearCart = (
    removeCartItemRequest?: RemoveCartItemRequest,
 ) => {
      return apiMutator<CartResponseEnvelope>(
      {url: `/cart`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: removeCartItemRequest
    },
      );
    }

/**
 * Sets the quantity of the cart line for the product identified by `{productId}` in the path. Functionally equivalent to `POST /cart`. Returns the updated cart.
 * @summary Set cart item quantity
 */
const updateCartItemById = (
    productId: string,
    updateCartItemByIdRequest: UpdateCartItemByIdRequest,
 ) => {
      return apiMutator<CartResponseEnvelope>(
      {url: `/cart/${productId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCartItemByIdRequest
    },
      );
    }

/**
 * Removes the cart line for the product identified by `{productId}` in the path from the authenticated user's cart. Returns the updated cart.
 * @summary Remove item from cart
 */
const removeCartItem = (
    productId: string,
 ) => {
      return apiMutator<CartResponseEnvelope>(
      {url: `/cart/${productId}`, method: 'DELETE'
    },
      );
    }

/**
 * Returns a lightweight summary of the authenticated user's cart.
 * @summary Get cart summary
 */
const getCartSummary = (

 ) => {
      return apiMutator<CartSummaryResponseEnvelope>(
      {url: `/cart/summary`, method: 'GET'
    },
      );
    }

/**
 * Converts the authenticated user's current cart into a new order. The cart is cleared upon success. An optional email address and order notes can be supplied in the request body. Returns the created order.
 * @summary Checkout (place order from cart)
 */
const checkout = (
    checkoutRequest?: CheckoutRequest,
 ) => {
      return apiMutator<CheckoutResponseEnvelope>(
      {url: `/cart/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkoutRequest
    },
      );
    }

/**
 * Returns a paginated list of orders.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary List orders (paginated)
 */
const listOrders = (
    params?: ListOrdersParams,
 ) => {
      return apiMutator<OrdersResponseEnvelope>(
      {url: `/orders`, method: 'GET',
        params
    },
      );
    }

/**
 * Creates a new order directly from the supplied payload.
 * @summary Create order
 */
const createOrder = (
    createOrderRequest: CreateOrderRequest,
 ) => {
      return apiMutator<OrderEnvelope>(
      {url: `/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrderRequest
    },
      );
    }

/**
 * Updates an existing order identified by id in the request body.
 * @summary Update order
 */
const updateOrder = (
    updateOrderRequest: UpdateOrderRequest,
 ) => {
      return apiMutator<OrderEnvelope>(
      {url: `/orders`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateOrderRequest
    },
      );
    }

/**
 * Permanently removes the order identified by id.
 * @summary Delete order
 */
const deleteOrder = (
    deleteOrderRequest: DeleteOrderRequest,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/orders`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteOrderRequest
    },
      );
    }

/**
 * Searches and filters orders via a JSON request body. Functionally equivalent to `GET /orders`.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary Search orders (DTO-friendly)
 */
const searchOrders = (
    searchOrdersRequest: SearchOrdersRequest,
 ) => {
      return apiMutator<OrdersResponseEnvelope>(
      {url: `/orders/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchOrdersRequest
    },
      );
    }

/**
 * Returns the full details of the order identified by `{id}`. Functionally equivalent to `GET /orders?id={id}`.
 * @summary Order details
 */
const getOrderById = (
    id: string,
 ) => {
      return apiMutator<OrderEnvelope>(
      {url: `/orders/${id}`, method: 'GET'
    },
      );
    }

/**
 * Updates the order identified by `{id}` in the path.
 * @summary Edit order
 */
const updateOrderById = (
    id: string,
    updateOrderByIdRequest: UpdateOrderByIdRequest,
 ) => {
      return apiMutator<OrderEnvelope>(
      {url: `/orders/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateOrderByIdRequest
    },
      );
    }

/**
 * Permanently removes the order identified by `id`.
 * @summary Delete order
 */
const deleteOrderById = (
    id: string,
 ) => {
      return apiMutator<SuccessResponse>(
      {url: `/orders/${id}`, method: 'DELETE'
    },
      );
    }

/**
 * Generates and returns the invoice for the order identified by `{id}` as a binary PDF file. The client should save or stream the response with an appropriate `Content-Disposition` header.
 * @summary Download order invoice (PDF)
 */
const getOrderInvoice = (
    id: string,
 ) => {
      return apiMutator<Blob>(
      {url: `/orders/${id}/invoice`, method: 'GET',
        responseType: 'blob'
    },
      );
    }

return {getHealth,getObservabilityEvents,getObservabilityHealth,getObservabilityMetrics,getObservabilityMetricsOverview,getObservabilityAuditLogs,getAccount,requestAccountDelete,confirmAccountDelete,login,signup,requestPasswordReset,confirmPasswordReset,refreshToken,refreshTokenWithPath,logoutAll,deleteExpiredTokens,listUsers,createUser,updateUser,deleteUser,getUserById,updateUserById,deleteUserById,searchUsers,createFeedbackRequest,listFeedbackRequests,updateFeedbackRequestStatus,listProducts,createProduct,updateProduct,deleteProduct,getProductById,updateProductById,deleteProductById,searchProducts,getCart,upsertCartItem,clearCart,updateCartItemById,removeCartItem,getCartSummary,checkout,listOrders,createOrder,updateOrder,deleteOrder,searchOrders,getOrderById,updateOrderById,deleteOrderById,getOrderInvoice}};
export type GetHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getHealth']>>>
export type GetObservabilityEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getObservabilityEvents']>>>
export type GetObservabilityHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getObservabilityHealth']>>>
export type GetObservabilityMetricsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getObservabilityMetrics']>>>
export type GetObservabilityMetricsOverviewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getObservabilityMetricsOverview']>>>
export type GetObservabilityAuditLogsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getObservabilityAuditLogs']>>>
export type GetAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getAccount']>>>
export type RequestAccountDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['requestAccountDelete']>>>
export type ConfirmAccountDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['confirmAccountDelete']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['login']>>>
export type SignupResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['signup']>>>
export type RequestPasswordResetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['requestPasswordReset']>>>
export type ConfirmPasswordResetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['confirmPasswordReset']>>>
export type RefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['refreshToken']>>>
export type RefreshTokenWithPathResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['refreshTokenWithPath']>>>
export type LogoutAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['logoutAll']>>>
export type DeleteExpiredTokensResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteExpiredTokens']>>>
export type ListUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['listUsers']>>>
export type CreateUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['createUser']>>>
export type UpdateUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateUser']>>>
export type DeleteUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteUser']>>>
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getUserById']>>>
export type UpdateUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateUserById']>>>
export type DeleteUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteUserById']>>>
export type SearchUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['searchUsers']>>>
export type CreateFeedbackRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['createFeedbackRequest']>>>
export type ListFeedbackRequestsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['listFeedbackRequests']>>>
export type UpdateFeedbackRequestStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateFeedbackRequestStatus']>>>
export type ListProductsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['listProducts']>>>
export type CreateProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['createProduct']>>>
export type UpdateProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateProduct']>>>
export type DeleteProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteProduct']>>>
export type GetProductByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getProductById']>>>
export type UpdateProductByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateProductById']>>>
export type DeleteProductByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteProductById']>>>
export type SearchProductsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['searchProducts']>>>
export type GetCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getCart']>>>
export type UpsertCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['upsertCartItem']>>>
export type ClearCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['clearCart']>>>
export type UpdateCartItemByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateCartItemById']>>>
export type RemoveCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['removeCartItem']>>>
export type GetCartSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getCartSummary']>>>
export type CheckoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['checkout']>>>
export type ListOrdersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['listOrders']>>>
export type CreateOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['createOrder']>>>
export type UpdateOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateOrder']>>>
export type DeleteOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteOrder']>>>
export type SearchOrdersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['searchOrders']>>>
export type GetOrderByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getOrderById']>>>
export type UpdateOrderByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['updateOrderById']>>>
export type DeleteOrderByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['deleteOrderById']>>>
export type GetOrderInvoiceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEcommerceDemoAPI>['getOrderInvoice']>>>
