/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Shopify PDP + Cart Exercise API
 * Minimal frontend-facing contract for the Shopify PDP + cart exercise.
 *
 * It mirrors the subset of the Shopify Storefront API domain the frontend
 * needs: fetch one product for the PDP, create/read a cart, and add lines.
 * Gift wrap and gift message are modeled as cart line attributes
 * (gift_wrap = "true", gift_message = "<free text>") on the product line.
 *
 * The real implementation calls the Storefront GraphQL API directly; this
 * document exists as the domain contract and codegen source (types, zod
 * schemas, MSW mocks).
 *
 * OpenAPI spec version: 3.0.0
 */
import { apiMutator } from '../app/utils/apiMutator';
/**
 * Resource identifier (Shopify GID, e.g. gid://shopify/Product/123)
 */
export type Id = string;

export interface Money {
  /** Decimal amount as string, as returned by the Storefront API */
  amount: string;
  /** ISO 4217 currency code */
  currencyCode: string;
}

export interface ErrorResponse {
  /** Technical error code or description */
  message: string;
  /** User-friendly error messages */
  errors?: string[];
}

export interface ProductImage {
  url: string;
  altText?: string;
}

export interface ProductVariant {
  id: Id;
  availableForSale: boolean;
  price: Money;
  compareAtPrice?: Money;
}

/**
 * Product detail for the PDP, with its default (first) variant.
 */
export interface Product {
  id: Id;
  title: string;
  vendor: string;
  image?: ProductImage;
  variant: ProductVariant;
}

/**
 * Key/value attribute attached to a cart line. Gift options use
 * gift_wrap = "true" and gift_message = "<free text>".
 */
export interface CartLineAttribute {
  key: string;
  value: string;
}

export interface CartLine {
  id: Id;
  /** @minimum 1 */
  quantity: number;
  /** Product title of the line's merchandise */
  title: string;
  vendor: string;
  image?: ProductImage;
  lineTotal: Money;
  attributes: CartLineAttribute[];
}

export interface Cart {
  id: Id;
  /** @minimum 0 */
  totalQuantity: number;
  subtotal: Money;
  lines: CartLine[];
}

/**
 * A variant to add to the cart, with optional gift attributes.
 */
export interface CartLineInput {
  merchandiseId: Id;
  /** @minimum 1 */
  quantity: number;
  attributes?: CartLineAttribute[];
}

export interface CreateCartRequest {
  /** Optional initial lines */
  lines?: CartLineInput[];
}

export interface AddCartLinesRequest {
  /** @minItems 1 */
  lines: CartLineInput[];
}

/**
 * Resource not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Validation failed
 */
export type ValidationErrorResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export const getShopifyPDPCartExerciseAPI = () => {
/**
 * Returns one product with its default variant, price and compare-at price.
 * @summary Get product detail for the PDP
 */
const getProduct = (
    productId: string,
 ) => {
      return apiMutator<Product>(
      {url: `/products/${productId}`, method: 'GET'
    },
      );
    }

/**
 * Creates a new cart, optionally with initial lines and gift attributes.
 * @summary Create a cart (Storefront cartCreate)
 */
const createCart = (
    createCartRequest?: CreateCartRequest,
 ) => {
      return apiMutator<Cart>(
      {url: `/cart`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCartRequest
    },
      );
    }

/**
 * Returns the cart with its lines, totals and gift wrap/message attributes.
 * @summary Get cart contents, including gift attributes
 */
const getCart = (
    cartId: string,
 ) => {
      return apiMutator<Cart>(
      {url: `/cart/${cartId}`, method: 'GET'
    },
      );
    }

/**
 * Adds variant lines with quantity and optional gift_wrap/gift_message attributes.
 * @summary Add product variant lines to the cart (Storefront cartLinesAdd)
 */
const addCartLines = (
    cartId: string,
    addCartLinesRequest: AddCartLinesRequest,
 ) => {
      return apiMutator<Cart>(
      {url: `/cart/${cartId}/lines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCartLinesRequest
    },
      );
    }

return {getProduct,createCart,getCart,addCartLines}};
export type GetProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShopifyPDPCartExerciseAPI>['getProduct']>>>
export type CreateCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShopifyPDPCartExerciseAPI>['createCart']>>>
export type GetCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShopifyPDPCartExerciseAPI>['getCart']>>>
export type AddCartLinesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShopifyPDPCartExerciseAPI>['addCartLines']>>>
