/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Shopify PDP + Cart Exercise API
 * Minimal frontend-facing contract for the Shopify PDP + cart exercise.
 *
 * It mirrors the subset of the Shopify Storefront API domain the frontend
 * needs: fetch one product for the PDP, create/read a cart, and add lines.
 * Gift wrap and gift message are modeled as cart line attributes
 * (gift_wrap = "true", gift_message = "<free text>") on the product line.
 *
 * The real implementation calls the Storefront GraphQL API directly; this
 * document exists as the domain contract and codegen source (types, zod
 * schemas, MSW mocks).
 *
 * OpenAPI spec version: 3.0.0
 */
import * as zod from 'zod';

/**
 * Returns one product with its default variant, price and compare-at price.
 * @summary Get product detail for the PDP
 */
export const GetProductParams = zod.object({
  "productId": zod.string().describe('Product identifier (Shopify GID)')
})

export const GetProductResponse = zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "title": zod.string(),
  "vendor": zod.string(),
  "image": zod.object({
  "url": zod.url(),
  "altText": zod.string().optional()
}).optional(),
  "variant": zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "availableForSale": zod.boolean(),
  "price": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "compareAtPrice": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}).optional()
})
}).describe('Product detail for the PDP, with its default (first) variant.')


/**
 * Creates a new cart, optionally with initial lines and gift attributes.
 * @summary Create a cart (Storefront cartCreate)
 */
export const createCartBodyLinesItemQuantityDefault = 1;



export const CreateCartBody = zod.object({
  "lines": zod.array(zod.object({
  "merchandiseId": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "quantity": zod.number().min(1).default(createCartBodyLinesItemQuantityDefault),
  "attributes": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.string()
}).describe('Key\/value attribute attached to a cart line. Gift options use\ngift_wrap = \"true\" and gift_message = \"<free text>\".\n')).optional()
}).describe('A variant to add to the cart, with optional gift attributes.')).optional().describe('Optional initial lines')
})

export const createCartResponseTotalQuantityMin = 0;




export const CreateCartResponse = zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "totalQuantity": zod.number().min(createCartResponseTotalQuantityMin),
  "subtotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "lines": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "quantity": zod.number().min(1),
  "title": zod.string().describe('Product title of the line\'s merchandise'),
  "vendor": zod.string(),
  "image": zod.object({
  "url": zod.url(),
  "altText": zod.string().optional()
}).optional(),
  "lineTotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "attributes": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.string()
}).describe('Key\/value attribute attached to a cart line. Gift options use\ngift_wrap = \"true\" and gift_message = \"<free text>\".\n'))
}))
})


/**
 * Returns the cart with its lines, totals and gift wrap/message attributes.
 * @summary Get cart contents, including gift attributes
 */
export const GetCartParams = zod.object({
  "cartId": zod.string().describe('Cart identifier (Shopify GID)')
})

export const getCartResponseTotalQuantityMin = 0;




export const GetCartResponse = zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "totalQuantity": zod.number().min(getCartResponseTotalQuantityMin),
  "subtotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "lines": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "quantity": zod.number().min(1),
  "title": zod.string().describe('Product title of the line\'s merchandise'),
  "vendor": zod.string(),
  "image": zod.object({
  "url": zod.url(),
  "altText": zod.string().optional()
}).optional(),
  "lineTotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "attributes": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.string()
}).describe('Key\/value attribute attached to a cart line. Gift options use\ngift_wrap = \"true\" and gift_message = \"<free text>\".\n'))
}))
})


/**
 * Adds variant lines with quantity and optional gift_wrap/gift_message attributes.
 * @summary Add product variant lines to the cart (Storefront cartLinesAdd)
 */
export const AddCartLinesParams = zod.object({
  "cartId": zod.string().describe('Cart identifier (Shopify GID)')
})

export const addCartLinesBodyLinesItemQuantityDefault = 1;




export const AddCartLinesBody = zod.object({
  "lines": zod.array(zod.object({
  "merchandiseId": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "quantity": zod.number().min(1).default(addCartLinesBodyLinesItemQuantityDefault),
  "attributes": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.string()
}).describe('Key\/value attribute attached to a cart line. Gift options use\ngift_wrap = \"true\" and gift_message = \"<free text>\".\n')).optional()
}).describe('A variant to add to the cart, with optional gift attributes.')).min(1)
})

export const addCartLinesResponseTotalQuantityMin = 0;




export const AddCartLinesResponse = zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "totalQuantity": zod.number().min(addCartLinesResponseTotalQuantityMin),
  "subtotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "lines": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier (Shopify GID, e.g. gid:\/\/shopify\/Product\/123)'),
  "quantity": zod.number().min(1),
  "title": zod.string().describe('Product title of the line\'s merchandise'),
  "vendor": zod.string(),
  "image": zod.object({
  "url": zod.url(),
  "altText": zod.string().optional()
}).optional(),
  "lineTotal": zod.object({
  "amount": zod.string().describe('Decimal amount as string, as returned by the Storefront API'),
  "currencyCode": zod.string().describe('ISO 4217 currency code')
}),
  "attributes": zod.array(zod.object({
  "key": zod.string(),
  "value": zod.string()
}).describe('Key\/value attribute attached to a cart line. Gift options use\ngift_wrap = \"true\" and gift_message = \"<free text>\".\n'))
}))
})
