/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import * as zod from 'zod';

/**
 * Public ping endpoint. Returns a simple liveness indicator confirming the API process is running.
 * @summary API health check
 */
export const GetHealthResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Live Server-Sent Events stream for demo dashboards.
 * Sends `metrics.snapshot` on connect, followed by periodic `metrics.updated` and `heartbeat` events.
 * @summary Observability SSE stream
 */
export const GetObservabilityEventsResponse = zod.unknown()


/**
 * Full JSON health snapshot for dashboard use.
 * Includes uptime, database status, memory, integrations, and system info.
 * Requires admin role.
 * @summary Health snapshot
 */
export const getObservabilityHealthResponseTwoDataDataUptimeSecondsMin = 0;



export const GetObservabilityHealthResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "success": zod.literal(true),
  "data": zod.object({
  "status": zod.enum(['ok', 'degraded']),
  "environment": zod.string(),
  "service": zod.string(),
  "nodeVersion": zod.string(),
  "uptimeSeconds": zod.number().min(getObservabilityHealthResponseTwoDataDataUptimeSecondsMin),
  "database": zod.object({
  "status": zod.enum(['connected', 'connecting', 'disconnected'])
}),
  "integrations": zod.object({
  "loki": zod.boolean().optional(),
  "posthog": zod.boolean().optional(),
  "otelEnabled": zod.boolean().optional()
}).optional(),
  "memory": zod.object({
  "heapUsedMb": zod.number(),
  "heapTotalMb": zod.number(),
  "rssMb": zod.number()
}).optional(),
  "system": zod.object({
  "platform": zod.string(),
  "cpuCount": zod.number(),
  "loadAvg": zod.array(zod.number())
}).optional(),
  "timestamp": zod.iso.datetime({"offset":true})
})
})
}))


/**
 * Raw Prometheus text (exposition format 0.0.4).
 * Intended for Prometheus scraping, not for browser clients.
 * Use `GET /observability/metrics/overview` for a JSON summary suitable for dashboards.
 * @summary Prometheus metrics
 */
export const GetObservabilityMetricsResponse = zod.string()


/**
 * Key operational metrics derived from Prometheus counters/histograms,
 * returned as structured JSON for dashboard KPI cards and charts.
 * Requires admin role.
 * @summary Metrics overview (JSON)
 */
export const getObservabilityMetricsOverviewResponseTwoDataDataHttpTotalRequestsMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataHttpTotalErrorsMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataHttpErrorRateMin = 0;
export const getObservabilityMetricsOverviewResponseTwoDataDataHttpErrorRateMax = 1;

export const getObservabilityMetricsOverviewResponseTwoDataDataHttpInFlightMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataAuthLoginSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataAuthLoginFailureMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataAuthSignupSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataBusinessCheckoutSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataBusinessOrdersCreatedMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataDatabaseQueriesTotalMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataDatabaseErrorsTotalMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataProcessUptimeSecondsMin = 0;

export const getObservabilityMetricsOverviewResponseTwoDataDataProcessHeapUsedMbMin = 0;



export const GetObservabilityMetricsOverviewResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "success": zod.literal(true),
  "data": zod.object({
  "http": zod.object({
  "totalRequests": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataHttpTotalRequestsMin),
  "totalErrors": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataHttpTotalErrorsMin),
  "errorRate": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataHttpErrorRateMin).max(getObservabilityMetricsOverviewResponseTwoDataDataHttpErrorRateMax).describe('Fraction of requests that returned 4xx\/5xx'),
  "inFlight": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataHttpInFlightMin),
  "latencyMs": zod.object({
  "p50": zod.number().describe('Median latency in ms'),
  "p95": zod.number().describe('95th-percentile latency in ms')
})
}),
  "auth": zod.object({
  "loginSuccess": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataAuthLoginSuccessMin).optional(),
  "loginFailure": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataAuthLoginFailureMin).optional(),
  "signupSuccess": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataAuthSignupSuccessMin).optional()
}),
  "business": zod.object({
  "checkoutSuccess": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataBusinessCheckoutSuccessMin).optional(),
  "ordersCreated": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataBusinessOrdersCreatedMin).optional()
}),
  "database": zod.object({
  "queriesTotal": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataDatabaseQueriesTotalMin).optional(),
  "errorsTotal": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataDatabaseErrorsTotalMin).optional()
}),
  "process": zod.object({
  "uptimeSeconds": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataProcessUptimeSecondsMin).optional(),
  "heapUsedMb": zod.number().min(getObservabilityMetricsOverviewResponseTwoDataDataProcessHeapUsedMbMin).optional()
}),
  "timestamp": zod.iso.datetime({"offset":true})
})
})
}))


/**
 * Returns the most recent audit events from the in-memory ring buffer (up to 200).
 * Events include auth flows, admin CRUD actions, and security blocks.
 * Requires admin role.
 * @summary Recent audit events
 */
export const getObservabilityAuditLogsQueryLimitDefault = 50;
export const getObservabilityAuditLogsQueryLimitMax = 200;



export const GetObservabilityAuditLogsQueryParams = zod.object({
  "actor": zod.string().optional().describe('Filter by actor user ID'),
  "action": zod.string().optional().describe('Filter by action name (e.g. auth.login.failed)'),
  "outcome": zod.enum(['success', 'failure']).optional().describe('Filter by outcome'),
  "since": zod.iso.datetime({"offset":true}).optional().describe('Return events after this ISO-8601 timestamp'),
  "limit": zod.number().min(1).max(getObservabilityAuditLogsQueryLimitMax).default(getObservabilityAuditLogsQueryLimitDefault).describe('Maximum number of events to return')
})

export const getObservabilityAuditLogsResponseTwoDataDataTotalMin = 0;



export const GetObservabilityAuditLogsResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "success": zod.literal(true),
  "data": zod.object({
  "items": zod.array(zod.object({
  "actor_user_id": zod.string(),
  "actor_role": zod.enum(['admin', 'user', 'anonymous']),
  "action": zod.string().describe('Dot-notation action name (e.g. auth.login.succeeded)'),
  "outcome": zod.enum(['success', 'failure']),
  "ip": zod.string().optional(),
  "user_agent": zod.string().optional(),
  "request_id": zod.string().optional(),
  "trace_id": zod.string().optional(),
  "target_type": zod.string().optional(),
  "target_id": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional(),
  "timestamp": zod.iso.datetime({"offset":true}),
  "level": zod.enum(['info', 'warn'])
})),
  "total": zod.number().min(getObservabilityAuditLogsResponseTwoDataDataTotalMin)
})
})
}))


/**
 * Returns the full profile of the currently authenticated user
 * @summary Current user info
 */
export const GetAccountResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Initiates the account-deletion flow for the authenticated user. A one-time confirmation token is sent to the user's email address. The token must then be submitted to `/account/delete-confirm` to complete the deletion.
 * @summary Request account deletion
 */
export const RequestAccountDeleteResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Completes the account-deletion flow. Validates the one-time token issued by `DELETE /account` and, if valid, permanently removes the user account.
 * @summary Confirm account deletion
 */
export const ConfirmAccountDeleteBody = zod.object({
  "token": zod.string().describe('One-time account deletion token (NOT a JWT).')
})

export const ConfirmAccountDeleteResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
 * @summary Login
 */
export const loginBodyPasswordMin = 8;



export const LoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(loginBodyPasswordMin)
})

export const LoginResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "token": zod.string().describe('Access JWT'),
  "refreshToken": zod.string().optional().describe('Refresh token if returned by backend'),
  "expiresIn": zod.number().optional().describe('Access token expiry in seconds')
})
}))


/**
 * Registers a new user account with optional image upload. Returns the newly created user profile on success.
 * @summary Signup
 */
export const signupBodyUsernameMin = 3;

export const signupBodyPasswordMin = 8;

export const signupBodyPasswordConfirmMin = 8;



export const SignupBody = zod.object({
  "email": zod.email(),
  "username": zod.string().min(signupBodyUsernameMin),
  "password": zod.string().min(signupBodyPasswordMin),
  "passwordConfirm": zod.string().min(signupBodyPasswordConfirmMin),
  "imageUrl": zod.url().optional()
})

export const SignupResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
 */
export const RequestPasswordResetBody = zod.object({
  "email": zod.email()
})

export const RequestPasswordResetResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user's password to the supplied value.
 */
export const confirmPasswordResetBodyPasswordMin = 8;

export const confirmPasswordResetBodyPasswordConfirmMin = 8;



export const ConfirmPasswordResetBody = zod.object({
  "token": zod.string().describe('One-time password reset token (NOT a JWT).'),
  "password": zod.string().min(confirmPasswordResetBodyPasswordMin),
  "passwordConfirm": zod.string().min(confirmPasswordResetBodyPasswordConfirmMin)
})

export const ConfirmPasswordResetResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Creates a new short-lived access token using a refresh token. The refresh token can be provided as a query parameter, path parameter, or retrieved from the `jwt` cookie.
 * @summary Refresh access token
 */
export const RefreshTokenResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "token": zod.string().describe('New access JWT'),
  "refreshToken": zod.string().optional().describe('New refresh token if returned by backend'),
  "expiresIn": zod.number().optional().describe('New access token expiry in seconds')
})
}))


/**
 * Creates a new short-lived access token using a refresh token provided in the URL path.
 * @summary Refresh access token with token in path
 */
export const RefreshTokenWithPathParams = zod.object({
  "token": zod.string().describe('Refresh token')
})

export const RefreshTokenWithPathResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "token": zod.string().describe('New access JWT'),
  "refreshToken": zod.string().optional().describe('New refresh token if returned by backend'),
  "expiresIn": zod.number().optional().describe('New access token expiry in seconds')
})
}))


/**
 * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
 * @summary Logout from all devices
 */
export const LogoutAllResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
 * @summary Remove expired tokens
 */
export const DeleteExpiredTokensResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Returns a paginated list of user accounts.
 * @summary List users (paginated)
 */
export const listUsersQueryPageDefault = 1;

export const listUsersQueryPageSizeDefault = 10;
export const listUsersQueryPageSizeMax = 100;




export const ListUsersQueryParams = zod.object({
  "page": zod.number().min(1).default(listUsersQueryPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listUsersQueryPageSizeMax).default(listUsersQueryPageSizeDefault),
  "text": zod.string().min(1).optional(),
  "id": zod.string().optional(),
  "email": zod.email().optional(),
  "username": zod.string().optional(),
  "active": zod.boolean().optional()
})

export const listUsersResponseTwoDataMetaPageDefault = 1;

export const listUsersResponseTwoDataMetaPageSizeDefault = 10;
export const listUsersResponseTwoDataMetaPageSizeMax = 100;

export const listUsersResponseTwoDataMetaTotalItemsMin = 0;

export const listUsersResponseTwoDataMetaTotalPagesMin = 0;



export const ListUsersResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(listUsersResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listUsersResponseTwoDataMetaPageSizeMax).default(listUsersResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(listUsersResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(listUsersResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
 * @summary Create user
 */
export const createUserBodyPasswordMin = 8;



export const CreateUserBody = zod.object({
  "email": zod.email(),
  "username": zod.string(),
  "password": zod.string().min(createUserBodyPasswordMin),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional()
})

export const CreateUserResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates an existing user's email or password. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUserBodyPasswordMin = 8;



export const UpdateUserBody = zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email().optional(),
  "username": zod.string().optional(),
  "password": zod.string().min(updateUserBodyPasswordMin).optional(),
  "imageUrl": zod.url().optional()
})

export const UpdateUserResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
 * @summary Delete user
 */
export const deleteUserBodyHardDeleteDefault = false;

export const DeleteUserBody = zod.object({
  "id": zod.string().describe('Resource identifier'),
  "hardDelete": zod.boolean().default(deleteUserBodyHardDeleteDefault)
})

export const DeleteUserResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
 * @summary User details
 */
export const GetUserByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const GetUserByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
 * @summary Edit user
 */
export const UpdateUserByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const updateUserByIdBodyPasswordMin = 8;



export const UpdateUserByIdBody = zod.object({
  "email": zod.email().optional(),
  "password": zod.string().min(updateUserByIdBodyPasswordMin).optional(),
  "username": zod.string().optional(),
  "imageUrl": zod.url().optional()
})

export const UpdateUserByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
 * @summary Delete user
 */
export const DeleteUserByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const DeleteUserByIdQueryParams = zod.object({
  "hardDelete": zod.boolean().optional()
})

export const DeleteUserByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
 * @summary Search users (DTO-friendly)
 */
export const searchUsersBodyPageDefault = 1;

export const searchUsersBodyPageSizeDefault = 10;
export const searchUsersBodyPageSizeMax = 100;




export const SearchUsersBody = zod.object({
  "page": zod.number().min(1).default(searchUsersBodyPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchUsersBodyPageSizeMax).default(searchUsersBodyPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "text": zod.string().min(1).optional().describe('Free-text search string'),
  "id": zod.string().optional().describe('Resource identifier'),
  "email": zod.email().optional(),
  "username": zod.string().optional(),
  "active": zod.boolean().optional()
})

export const searchUsersResponseTwoDataMetaPageDefault = 1;

export const searchUsersResponseTwoDataMetaPageSizeDefault = 10;
export const searchUsersResponseTwoDataMetaPageSizeMax = 100;

export const searchUsersResponseTwoDataMetaTotalItemsMin = 0;

export const searchUsersResponseTwoDataMetaTotalPagesMin = 0;



export const SearchUsersResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "username": zod.string(),
  "admin": zod.boolean().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(searchUsersResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchUsersResponseTwoDataMetaPageSizeMax).default(searchUsersResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(searchUsersResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(searchUsersResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Creates a user feedback/contact request and notifies admins via email.
 * @summary Submit contact request
 */
export const CreateFeedbackRequestBody = zod.object({
  "name": zod.string().optional(),
  "email": zod.email(),
  "subject": zod.string(),
  "message": zod.string()
})

export const CreateFeedbackRequestResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "name": zod.string().optional(),
  "email": zod.email(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.enum(['new', 'in_progress', 'resolved', 'spam']),
  "adminNotes": zod.string().optional(),
  "respondedAt": zod.iso.datetime({"offset":true}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Returns feedback/contact requests for admin review.
 * @summary List feedback requests
 */
export const listFeedbackRequestsBodyPageDefault = 1;

export const listFeedbackRequestsBodyPageSizeDefault = 10;
export const listFeedbackRequestsBodyPageSizeMax = 100;




export const ListFeedbackRequestsBody = zod.object({
  "page": zod.number().min(1).default(listFeedbackRequestsBodyPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listFeedbackRequestsBodyPageSizeMax).default(listFeedbackRequestsBodyPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "text": zod.string().min(1).optional().describe('Free-text search string'),
  "status": zod.enum(['new', 'in_progress', 'resolved', 'spam']).optional(),
  "email": zod.email().optional()
})

export const listFeedbackRequestsResponseTwoDataMetaPageDefault = 1;

export const listFeedbackRequestsResponseTwoDataMetaPageSizeDefault = 10;
export const listFeedbackRequestsResponseTwoDataMetaPageSizeMax = 100;

export const listFeedbackRequestsResponseTwoDataMetaTotalItemsMin = 0;

export const listFeedbackRequestsResponseTwoDataMetaTotalPagesMin = 0;



export const ListFeedbackRequestsResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "name": zod.string().optional(),
  "email": zod.email(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.enum(['new', 'in_progress', 'resolved', 'spam']),
  "adminNotes": zod.string().optional(),
  "respondedAt": zod.iso.datetime({"offset":true}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(listFeedbackRequestsResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listFeedbackRequestsResponseTwoDataMetaPageSizeMax).default(listFeedbackRequestsResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(listFeedbackRequestsResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(listFeedbackRequestsResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Updates status/notes of a feedback request.
 * @summary Update feedback request status
 */
export const UpdateFeedbackRequestStatusParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const UpdateFeedbackRequestStatusBody = zod.object({
  "status": zod.enum(['new', 'in_progress', 'resolved', 'spam']).optional(),
  "adminNotes": zod.string().optional()
})

export const UpdateFeedbackRequestStatusResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "name": zod.string().optional(),
  "email": zod.email(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.enum(['new', 'in_progress', 'resolved', 'spam']),
  "adminNotes": zod.string().optional(),
  "respondedAt": zod.iso.datetime({"offset":true}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Returns a paginated list of products.
 * @summary List products (paginated)
 */
export const listProductsQueryPageDefault = 1;

export const listProductsQueryPageSizeDefault = 10;
export const listProductsQueryPageSizeMax = 100;


export const listProductsQueryMinPriceMin = 0;

export const listProductsQueryMaxPriceMin = 0;



export const ListProductsQueryParams = zod.object({
  "page": zod.number().min(1).default(listProductsQueryPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listProductsQueryPageSizeMax).default(listProductsQueryPageSizeDefault),
  "text": zod.string().min(1).optional(),
  "productId": zod.string().optional(),
  "minPrice": zod.number().min(listProductsQueryMinPriceMin).optional(),
  "maxPrice": zod.number().min(listProductsQueryMaxPriceMin).optional()
})

export const listProductsResponseTwoDataItemsItemPriceMin = 0;

export const listProductsResponseTwoDataMetaPageDefault = 1;

export const listProductsResponseTwoDataMetaPageSizeDefault = 10;
export const listProductsResponseTwoDataMetaPageSizeMax = 100;

export const listProductsResponseTwoDataMetaTotalItemsMin = 0;

export const listProductsResponseTwoDataMetaTotalPagesMin = 0;



export const ListProductsResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(listProductsResponseTwoDataItemsItemPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(listProductsResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listProductsResponseTwoDataMetaPageSizeMax).default(listProductsResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(listProductsResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(listProductsResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Creates a new product with optional image upload
 * @summary Create product
 */
export const createProductBodyPriceMin = 0;



export const CreateProductBody = zod.object({
  "title": zod.string(),
  "price": zod.number().min(createProductBodyPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional()
})

export const createProductResponseTwoDataPriceMin = 0;



export const CreateProductResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(createProductResponseTwoDataPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates an existing product with optional image upload
 * @summary Edit product
 */
export const updateProductBodyPriceMin = 0;



export const UpdateProductBody = zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number().min(updateProductBodyPriceMin),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional()
})

export const updateProductResponseTwoDataPriceMin = 0;



export const UpdateProductResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(updateProductResponseTwoDataPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Deletes the product identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record
 * @summary Delete product
 */
export const deleteProductBodyHardDeleteDefault = false;

export const DeleteProductBody = zod.object({
  "id": zod.string().describe('Resource identifier'),
  "hardDelete": zod.boolean().default(deleteProductBodyHardDeleteDefault)
})

export const DeleteProductResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Returns the full details of the product identified by `{id}`. Functionally equivalent to `GET /products?id={id}`.
 * @summary Product details
 */
export const GetProductByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const getProductByIdResponseTwoDataPriceMin = 0;



export const GetProductByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(getProductByIdResponseTwoDataPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates the product identified by `{id}` in the path with optional image upload. Functionally equivalent to `PUT /products` with the id in the body.
 * @summary Edit product
 */
export const UpdateProductByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const updateProductByIdBodyPriceMin = 0;



export const UpdateProductByIdBody = zod.object({
  "title": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number().min(updateProductByIdBodyPriceMin),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional()
})

export const updateProductByIdResponseTwoDataPriceMin = 0;



export const UpdateProductByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(updateProductByIdResponseTwoDataPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Deletes the product identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /products`.
 * @summary Delete product
 */
export const DeleteProductByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const DeleteProductByIdQueryParams = zod.object({
  "hardDelete": zod.boolean().optional()
})

export const DeleteProductByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Searches and filters products via a JSON request body. Functionally equivalent to `GET /products` with query parameters.
 * @summary Search products (DTO-friendly)
 */
export const searchProductsBodyPageDefault = 1;

export const searchProductsBodyPageSizeDefault = 10;
export const searchProductsBodyPageSizeMax = 100;


export const searchProductsBodyMinPriceMin = 0;

export const searchProductsBodyMaxPriceMin = 0;



export const SearchProductsBody = zod.object({
  "page": zod.number().min(1).default(searchProductsBodyPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchProductsBodyPageSizeMax).default(searchProductsBodyPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "text": zod.string().min(1).optional().describe('Free-text search string'),
  "id": zod.string().optional().describe('Resource identifier'),
  "minPrice": zod.number().min(searchProductsBodyMinPriceMin).optional(),
  "maxPrice": zod.number().min(searchProductsBodyMaxPriceMin).optional(),
  "category": zod.string().optional(),
  "tag": zod.string().optional()
})

export const searchProductsResponseTwoDataItemsItemPriceMin = 0;

export const searchProductsResponseTwoDataMetaPageDefault = 1;

export const searchProductsResponseTwoDataMetaPageSizeDefault = 10;
export const searchProductsResponseTwoDataMetaPageSizeMax = 100;

export const searchProductsResponseTwoDataMetaTotalItemsMin = 0;

export const searchProductsResponseTwoDataMetaTotalPagesMin = 0;



export const SearchProductsResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(searchProductsResponseTwoDataItemsItemPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(searchProductsResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchProductsResponseTwoDataMetaPageSizeMax).default(searchProductsResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(searchProductsResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(searchProductsResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Returns all items currently in the authenticated user's cart along with a computed summary
 * @summary Get cart
 */

export const getCartResponseTwoDataSummaryItemsCountMin = 0;

export const getCartResponseTwoDataSummaryTotalQuantityMin = 0;

export const getCartResponseTwoDataSummaryTotalMin = 0;



export const GetCartResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})),
  "summary": zod.object({
  "itemsCount": zod.number().min(getCartResponseTwoDataSummaryItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(getCartResponseTwoDataSummaryTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(getCartResponseTwoDataSummaryTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
})
}))


/**
 * Adds or edit a product to the authenticated user's cart. Returns the updated cart.
 * @summary Add/Edit cart item
 */



export const UpsertCartItemBody = zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})


export const upsertCartItemResponseTwoDataSummaryItemsCountMin = 0;

export const upsertCartItemResponseTwoDataSummaryTotalQuantityMin = 0;

export const upsertCartItemResponseTwoDataSummaryTotalMin = 0;



export const UpsertCartItemResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})),
  "summary": zod.object({
  "itemsCount": zod.number().min(upsertCartItemResponseTwoDataSummaryItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(upsertCartItemResponseTwoDataSummaryTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(upsertCartItemResponseTwoDataSummaryTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
})
}))


/**
 * Clear cart or, ir productId is set, removes a specific product from the authenticated user's cart. Returns the updated cart (can be empty)
 * @summary Empty cart or, if productId is set, remove target cart item
 */
export const ClearCartBody = zod.object({
  "productId": zod.string().optional().describe('Resource identifier')
})


export const clearCartResponseTwoDataSummaryItemsCountMin = 0;

export const clearCartResponseTwoDataSummaryTotalQuantityMin = 0;

export const clearCartResponseTwoDataSummaryTotalMin = 0;



export const ClearCartResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})),
  "summary": zod.object({
  "itemsCount": zod.number().min(clearCartResponseTwoDataSummaryItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(clearCartResponseTwoDataSummaryTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(clearCartResponseTwoDataSummaryTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
})
}))


/**
 * Sets the quantity of the cart line for the product identified by `{productId}` in the path. Functionally equivalent to `POST /cart`. Returns the updated cart.
 * @summary Set cart item quantity
 */
export const UpdateCartItemByIdParams = zod.object({
  "productId": zod.string().describe('Product identifier')
})




export const UpdateCartItemByIdBody = zod.object({
  "productId": zod.string().optional().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})


export const updateCartItemByIdResponseTwoDataSummaryItemsCountMin = 0;

export const updateCartItemByIdResponseTwoDataSummaryTotalQuantityMin = 0;

export const updateCartItemByIdResponseTwoDataSummaryTotalMin = 0;



export const UpdateCartItemByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})),
  "summary": zod.object({
  "itemsCount": zod.number().min(updateCartItemByIdResponseTwoDataSummaryItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(updateCartItemByIdResponseTwoDataSummaryTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(updateCartItemByIdResponseTwoDataSummaryTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
})
}))


/**
 * Removes the cart line for the product identified by `{productId}` in the path from the authenticated user's cart. Returns the updated cart.
 * @summary Remove item from cart
 */
export const RemoveCartItemParams = zod.object({
  "productId": zod.string().describe('Product identifier')
})


export const removeCartItemResponseTwoDataSummaryItemsCountMin = 0;

export const removeCartItemResponseTwoDataSummaryTotalQuantityMin = 0;

export const removeCartItemResponseTwoDataSummaryTotalMin = 0;



export const RemoveCartItemResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})),
  "summary": zod.object({
  "itemsCount": zod.number().min(removeCartItemResponseTwoDataSummaryItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(removeCartItemResponseTwoDataSummaryTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(removeCartItemResponseTwoDataSummaryTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
})
}))


/**
 * Returns a lightweight summary of the authenticated user's cart.
 * @summary Get cart summary
 */
export const getCartSummaryResponseTwoDataItemsCountMin = 0;

export const getCartSummaryResponseTwoDataTotalQuantityMin = 0;

export const getCartSummaryResponseTwoDataTotalMin = 0;



export const GetCartSummaryResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "itemsCount": zod.number().min(getCartSummaryResponseTwoDataItemsCountMin).describe('Number of distinct cart lines\/items'),
  "totalQuantity": zod.number().min(getCartSummaryResponseTwoDataTotalQuantityMin).describe('Sum of quantities across all items'),
  "total": zod.number().min(getCartSummaryResponseTwoDataTotalMin).describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
  "currency": zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
})
}))


/**
 * Converts the authenticated user's current cart into a new order. The cart is cleared upon success. An optional email address and order notes can be supplied in the request body. Returns the created order.
 * @summary Checkout (place order from cart)
 */
export const CheckoutBody = zod.object({
  "email": zod.email().optional(),
  "notes": zod.string().optional().describe('Optional order notes')
})

export const checkoutResponseTwoDataOrderItemsItemProductPriceMin = 0;


export const checkoutResponseTwoDataOrderTotalMin = 0;



export const CheckoutResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "order": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(checkoutResponseTwoDataOrderItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(checkoutResponseTwoDataOrderTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "message": zod.string().optional()
})
}))


/**
 * Returns a paginated list of orders.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary List orders (paginated)
 */
export const listOrdersQueryPageDefault = 1;

export const listOrdersQueryPageSizeDefault = 10;
export const listOrdersQueryPageSizeMax = 100;



export const ListOrdersQueryParams = zod.object({
  "page": zod.number().min(1).default(listOrdersQueryPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listOrdersQueryPageSizeMax).default(listOrdersQueryPageSizeDefault),
  "id": zod.string().optional(),
  "userId": zod.string().optional(),
  "productId": zod.string().optional(),
  "email": zod.email().optional()
})

export const listOrdersResponseTwoDataItemsItemItemsItemProductPriceMin = 0;


export const listOrdersResponseTwoDataItemsItemTotalMin = 0;

export const listOrdersResponseTwoDataMetaPageDefault = 1;

export const listOrdersResponseTwoDataMetaPageSizeDefault = 10;
export const listOrdersResponseTwoDataMetaPageSizeMax = 100;

export const listOrdersResponseTwoDataMetaTotalItemsMin = 0;

export const listOrdersResponseTwoDataMetaTotalPagesMin = 0;



export const ListOrdersResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(listOrdersResponseTwoDataItemsItemItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(listOrdersResponseTwoDataItemsItemTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(listOrdersResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(listOrdersResponseTwoDataMetaPageSizeMax).default(listOrdersResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(listOrdersResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(listOrdersResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Creates a new order directly from the supplied payload.
 * @summary Create order
 */




export const CreateOrderBody = zod.object({
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})).min(1)
}).describe('Create a new order.')

export const createOrderResponseTwoDataItemsItemProductPriceMin = 0;


export const createOrderResponseTwoDataTotalMin = 0;



export const CreateOrderResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(createOrderResponseTwoDataItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(createOrderResponseTwoDataTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates an existing order identified by id in the request body.
 * @summary Update order
 */




export const UpdateOrderBody = zod.object({
  "id": zod.string().describe('Resource identifier'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']).optional().describe('Updated order status'),
  "userId": zod.string().optional().describe('Resource identifier'),
  "email": zod.email().optional(),
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})).min(1).optional()
})

export const updateOrderResponseTwoDataItemsItemProductPriceMin = 0;


export const updateOrderResponseTwoDataTotalMin = 0;



export const UpdateOrderResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(updateOrderResponseTwoDataItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(updateOrderResponseTwoDataTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Permanently removes the order identified by id.
 * @summary Delete order
 */
export const DeleteOrderBody = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const DeleteOrderResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Searches and filters orders via a JSON request body. Functionally equivalent to `GET /orders`.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary Search orders (DTO-friendly)
 */
export const searchOrdersBodyPageDefault = 1;

export const searchOrdersBodyPageSizeDefault = 10;
export const searchOrdersBodyPageSizeMax = 100;



export const SearchOrdersBody = zod.object({
  "page": zod.number().min(1).default(searchOrdersBodyPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchOrdersBodyPageSizeMax).default(searchOrdersBodyPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "id": zod.string().optional().describe('Resource identifier'),
  "userId": zod.string().optional().describe('Resource identifier'),
  "productId": zod.string().optional().describe('Resource identifier'),
  "email": zod.email().optional()
})

export const searchOrdersResponseTwoDataItemsItemItemsItemProductPriceMin = 0;


export const searchOrdersResponseTwoDataItemsItemTotalMin = 0;

export const searchOrdersResponseTwoDataMetaPageDefault = 1;

export const searchOrdersResponseTwoDataMetaPageSizeDefault = 10;
export const searchOrdersResponseTwoDataMetaPageSizeMax = 100;

export const searchOrdersResponseTwoDataMetaTotalItemsMin = 0;

export const searchOrdersResponseTwoDataMetaTotalPagesMin = 0;



export const SearchOrdersResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(searchOrdersResponseTwoDataItemsItemItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(searchOrdersResponseTwoDataItemsItemTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})),
  "meta": zod.object({
  "page": zod.number().min(1).default(searchOrdersResponseTwoDataMetaPageDefault).describe('1-based page index'),
  "pageSize": zod.number().min(1).max(searchOrdersResponseTwoDataMetaPageSizeMax).default(searchOrdersResponseTwoDataMetaPageSizeDefault).describe('Optional override; server may clamp to a max'),
  "totalItems": zod.number().min(searchOrdersResponseTwoDataMetaTotalItemsMin),
  "totalPages": zod.number().min(searchOrdersResponseTwoDataMetaTotalPagesMin)
})
})
}))


/**
 * Returns the full details of the order identified by `{id}`. Functionally equivalent to `GET /orders?id={id}`.
 * @summary Order details
 */
export const GetOrderByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const getOrderByIdResponseTwoDataItemsItemProductPriceMin = 0;


export const getOrderByIdResponseTwoDataTotalMin = 0;



export const GetOrderByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(getOrderByIdResponseTwoDataItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(getOrderByIdResponseTwoDataTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Updates the order identified by `{id}` in the path.
 * @summary Edit order
 */
export const UpdateOrderByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})





export const UpdateOrderByIdBody = zod.object({
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']).optional().describe('Updated order status'),
  "userId": zod.string().optional().describe('Resource identifier'),
  "email": zod.email().optional(),
  "items": zod.array(zod.object({
  "productId": zod.string().describe('Resource identifier'),
  "quantity": zod.number().min(1)
})).min(1).optional()
})

export const updateOrderByIdResponseTwoDataItemsItemProductPriceMin = 0;


export const updateOrderByIdResponseTwoDataTotalMin = 0;



export const UpdateOrderByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "userId": zod.string().describe('Resource identifier'),
  "email": zod.email(),
  "items": zod.array(zod.object({
  "product": zod.object({
  "id": zod.string().describe('Resource identifier'),
  "title": zod.string(),
  "price": zod.number().min(updateOrderByIdResponseTwoDataItemsItemProductPriceMin),
  "description": zod.string().optional(),
  "active": zod.boolean().optional(),
  "imageUrl": zod.url().optional(),
  "categories": zod.array(zod.string()).optional(),
  "tags": zod.array(zod.string()).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "deletedAt": zod.iso.datetime({"offset":true}).optional()
}),
  "quantity": zod.number().min(1)
})),
  "total": zod.number().min(updateOrderByIdResponseTwoDataTotalMin),
  "notes": zod.string().optional().describe('Optional order notes'),
  "status": zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})
}))


/**
 * Permanently removes the order identified by `id`.
 * @summary Delete order
 */
export const DeleteOrderByIdParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const DeleteOrderByIdResponse = zod.object({
  "success": zod.literal(true),
  "status": zod.number(),
  "message": zod.string()
})


/**
 * Generates and returns the invoice for the order identified by `{id}` as a binary PDF file. The client should save or stream the response with an appropriate `Content-Disposition` header.
 * @summary Download order invoice (PDF)
 */
export const GetOrderInvoiceParams = zod.object({
  "id": zod.string().describe('Resource identifier')
})

export const GetOrderInvoiceResponse = zod.unknown()
